apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: dg0300-lifesub-ns
type: Opaque
stringData:
  JWT_SECRET_KEY: "ddJnGgLAOKlgLxB8IUOmXxu3HetRCO+c6p4d3rZt+LU="
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
